// Ce fichier contient les données initiales extraites de l'application frontend
// pour peupler la base de données de développement.

export const initialUsers = [
    { id: 'assistant-id', name: 'Assistant KMER ZONE', email: 'assistant@kmerzone.com', password: 'password', role: 'customer' },
    { id: 'customer-1', name: 'Client Test', email: 'customer@example.com', password: 'password', role: 'customer' },
    // Vendeurs (noms corrigés pour correspondre aux boutiques)
    { id: 'seller-1', name: 'Aïcha Bakari', email: 'seller@example.com', password: 'password', role: 'seller' },
    { id: 'seller-2', name: 'Jeanne Abena', email: 'mamaafrica@example.com', password: 'password', role: 'seller' },
    { id: 'seller-3', name: 'Paul Kouam', email: 'electro@example.com', password: 'password', role: 'seller' },
    { id: 'seller-4', name: 'Céline Ngassa', email: 'soaps@example.com', password: 'password', role: 'seller' },
    { id: 'seller-5', name: 'Franck Essomba', email: 'yaoundestyle@example.com', password: 'password', role: 'seller' },
    { id: 'seller-6', name: 'Pierre Kamdem', email: 'bafoussam@example.com', password: 'password', role: 'seller' },
    { id: 'seller-7', name: 'Sarah Eko', email: 'limbearts@example.com', password: 'password', role: 'seller' },
    { id: 'seller-8', name: 'David Lobe', email: 'kribidigital@example.com', password: 'password', role: 'seller' },
    // Admin & Agents
    { id: 'admin-1', name: 'Super Admin', email: 'superadmin@example.com', password: 'password', role: 'superadmin' },
    { id: 'agent-1', name: 'Paul Atanga', email: 'agent1@example.com', password: 'password', role: 'delivery_agent' },
    { id: 'agent-2', name: 'Brenda Biya', email: 'agent2@example.com', password: 'password', role: 'delivery_agent' },
    { id: 'depot-agent-1', name: 'Agent Dépôt', email: 'depot@example.com', password: 'password', role: 'depot_agent' },
];

export const initialCategories = [
    // Catégories Principales
    { id: 'cat-vetements', name: 'Vêtements et chaussures' },
    { id: 'cat-accessoires', name: 'Accessoires & bijoux' },
    { id: 'cat-beaute', name: 'Beauté' },
    { id: 'cat-mobilier', name: 'Mobilier (Meubles)' },
    { id: 'cat-electronique', name: 'Électronique' },
    { id: 'cat-textile', name: 'Textile maison' },
    { id: 'cat-bureau', name: 'Fournitures de bureau' },
    { id: 'cat-animaux', name: 'Produits pour animaux' },
    { id: 'cat-loisirs', name: 'Loisirs & Créativité' },
    { id: 'cat-jardin', name: 'Maison & Jardin' },
    { id: 'cat-electronique-grand-public', name: 'Électronique grand public' },
    { id: 'cat-enfants', name: 'Produits pour enfants et scolaires' },
    // Sous-catégories
    { id: 'sub-vetements', parentId: 'cat-vetements', name: 'Vêtements' },
    { id: 'sub-chaussures', parentId: 'cat-vetements', name: 'Chaussures' },
    { id: 'sub-sacs', parentId: 'cat-accessoires', name: 'Sacs' },
    { id: 'sub-montres', parentId: 'cat-accessoires', name: 'Montres' },
    { id: 'sub-lunettes', parentId: 'cat-accessoires', name: 'Lunettes' },
    { id: 'sub-bijoux', parentId: 'cat-accessoires', name: 'Bijoux' },
    { id: 'sub-accessoires-cheveux', parentId: 'cat-accessoires', name: 'Accessoires cheveux' },
    { id: 'sub-cosmetiques', parentId: 'cat-beaute', name: 'Cosmétiques' },
    { id: 'sub-parfums', parentId: 'cat-beaute', name: 'Parfums' },
    { id: 'sub-chaises', parentId: 'cat-mobilier', name: 'Chaises' },
    { id: 'sub-autres-meubles', parentId: 'cat-mobilier', name: 'Autres meubles' },
    { id: 'sub-chargeurs-cables-batteries', parentId: 'cat-electronique', name: 'Chargeurs, câbles, batteries' },
    { id: 'sub-rideaux', parentId: 'cat-textile', name: 'Rideaux' },
    { id: 'sub-autres-textiles', parentId: 'cat-textile', name: 'Autres textiles domestiques' },
    { id: 'sub-papeterie', parentId: 'cat-bureau', name: 'Papeterie' },
    { id: 'sub-office-goods', parentId: 'cat-bureau', name: 'Office goods' },
    { id: 'sub-accessoires-animaux', parentId: 'cat-animaux', name: 'Accessoires pour animaux' },
    { id: 'sub-artisanat-jeux', parentId: 'cat-loisirs', name: 'Hobbies, artisanat, jeux' },
    { id: 'sub-decoration', parentId: 'cat-jardin', name: 'Décoration intérieure, luminaire, objets festifs' },
    { id: 'sub-telephones-casques', parentId: 'cat-electronique-grand-public', name: 'Téléphones, casques, électroménagers' },
    { id: 'sub-jouets-fournitures', parentId: 'cat-enfants', name: 'Jouets, fournitures scolaires' },
];

export const initialProducts = [
    { id: '1', name: 'Ndolé Royal', price: 3500, promotionPrice: 3000, imageUrls: ['https://picsum.photos/seed/ndole/400'], vendor: 'Mama Africa', description: "Le plat national du Cameroun...", stock: 15, categoryId: 'sub-autres-textiles', status: 'published' },
    { id: '2', name: 'Robe en Tissu Pagne', price: 15000, imageUrls: ['https://picsum.photos/seed/robe/400'], vendor: 'Kmer Fashion', description: "Une robe élégante...", stock: 8, categoryId: 'sub-vetements', status: 'published', brand: 'Kmer Fashion' },
    { id: '3', name: 'Savon Artisanal à l\'huile d\'olive', price: 1500, imageUrls: ['https://picsum.photos/seed/savon/400'], vendor: 'Douala Soaps', description: "Un savon artisanal...", stock: 50, categoryId: 'sub-cosmetiques', status: 'published', brand: 'Douala Soaps' },
    { id: '4', name: 'Smartphone Pro Max', price: 75000, promotionPrice: 69900, imageUrls: ['https://picsum.photos/seed/phone/400'], vendor: 'Electro Plus', description: "Un smartphone performant...", stock: 4, categoryId: 'sub-telephones-casques', status: 'published', brand: 'TechPro' },
    { id: '5', name: 'Miel d\'Oku', price: 5000, imageUrls: ['https://picsum.photos/seed/miel/400'], vendor: 'Mama Africa', description: "Un miel blanc rare...", stock: 25, categoryId: 'sub-autres-textiles', status: 'published' },
    { id: '6', name: 'Sandales en cuir', price: 8000, imageUrls: ['https://picsum.photos/seed/sandales/400'], vendor: 'Kmer Fashion', description: "Sandales en cuir véritable...", stock: 10, categoryId: 'sub-chaussures', status: 'draft', brand: 'Kmer Fashion' },
    { id: '7', name: 'Poulet DG', price: 6500, imageUrls: ['https://picsum.photos/seed/pouletdg/400'], vendor: 'Mama Africa', description: "Un plat de fête succulent...", stock: 12, categoryId: 'sub-autres-textiles', status: 'published' },
    { id: '8', name: 'Jus de Bissap Naturel', price: 1000, imageUrls: ['https://picsum.photos/seed/bissap/400'], vendor: 'Mama Africa', description: "Boisson rafraîchissante...", stock: 30, categoryId: 'sub-autres-textiles', status: 'published' },
    { id: '9', name: 'Beignets Haricots Bouillie', price: 1500, imageUrls: ['https://picsum.photos/seed/beignets/400'], vendor: 'Mama Africa', description: "Le petit-déjeuner camerounais...", stock: 20, categoryId: 'sub-autres-textiles', status: 'published' },
    { id: '10', name: 'Chemise en Toghu', price: 25000, imageUrls: ['https://picsum.photos/seed/toghu/400'], vendor: 'Kmer Fashion', description: "Chemise de cérémonie pour homme...", stock: 5, categoryId: 'sub-vetements', status: 'published', brand: 'Kmer Fashion' },
    { id: '11', name: 'Poivre de Penja', price: 4500, imageUrls: ['https://picsum.photos/seed/poivre/400'], vendor: 'Mama Africa', description: "Considéré comme l'un des meilleurs poivres...", stock: 40, categoryId: 'sub-autres-textiles', status: 'published' },
    { id: '12', name: 'Sac à main en pagne', price: 12000, imageUrls: ['https://picsum.photos/seed/sacpagne/400'], vendor: 'Kmer Fashion', description: "Accessoirisez votre tenue...", stock: 15, categoryId: 'sub-sacs', status: 'published', brand: 'Kmer Fashion' },
    { id: '13', name: 'Téléviseur LED 32"', price: 85000, imageUrls: ['https://picsum.photos/seed/tv/400'], vendor: 'Electro Plus', description: "Un téléviseur LED de 32 pouces...", stock: 9, categoryId: 'sub-telephones-casques', status: 'published', brand: 'ViewSonic' },
    { id: '14', name: 'Fer à repasser', price: 7500, imageUrls: ['https://picsum.photos/seed/fer/400'], vendor: 'Electro Plus', description: "Simple, efficace et durable.", stock: 25, categoryId: 'sub-telephones-casques', status: 'published', brand: 'Generic' },
    { id: '15', name: 'Blender / Mixeur', price: 18000, imageUrls: ['https://picsum.photos/seed/blender/400'], vendor: 'Electro Plus', description: "Un mixeur puissant...", stock: 18, categoryId: 'sub-telephones-casques', status: 'published', brand: 'MixWell' },
    { id: '16', name: 'Savon noir gommant', price: 2500, imageUrls: ['https://picsum.photos/seed/savonnoir/400'], vendor: 'Douala Soaps', description: "Savon noir africain...", stock: 40, categoryId: 'sub-cosmetiques', status: 'published', brand: 'Douala Soaps' },
    { id: '17', name: 'Huile de coco vierge', price: 4000, imageUrls: ['https://picsum.photos/seed/coco/400'], vendor: 'Douala Soaps', description: "Huile de coco 100% pure...", stock: 30, categoryId: 'sub-cosmetiques', status: 'published', brand: 'Douala Soaps' },
    { id: '18', name: 'Beurre de karité', price: 3000, imageUrls: ['https://picsum.photos/seed/karite/400'], vendor: 'Douala Soaps', description: "Beurre de karité brut...", stock: 60, categoryId: 'sub-cosmetiques', status: 'published', brand: 'Douala Soaps' },
    { id: '19', name: 'Baskets de Ville', price: 22000, imageUrls: ['https://picsum.photos/seed/baskets/400'], vendor: 'Kmer Fashion', description: "Baskets confortables...", stock: 20, categoryId: 'sub-chaussures', status: 'published', brand: 'CityWalkers' },
    { id: '20', name: 'Eau de Parfum "Sawa"', price: 28000, imageUrls: ['https://picsum.photos/seed/parfum/400'], vendor: 'Douala Soaps', description: "Un parfum boisé et épicé...", stock: 15, categoryId: 'sub-parfums', status: 'published', brand: 'Douala Soaps' },
    { id: '21', name: 'Fauteuil en Rotin', price: 45000, imageUrls: ['https://picsum.photos/seed/rotin/400'], vendor: 'Electro Plus', description: "Fauteuil artisanal en rotin...", stock: 5, categoryId: 'sub-chaises', status: 'published', brand: 'HomeDecor' },
    { id: '22', name: 'Masque décoratif Fang', price: 18000, imageUrls: ['https://picsum.photos/seed/masque/400'], vendor: 'Kmer Fashion', description: "Authentique masque décoratif...", stock: 10, categoryId: 'sub-decoration', status: 'published', brand: 'Artisanat Local' },
    { id: '23', name: 'Lampe de chevet "Wouri"', price: 13500, imageUrls: ['https://picsum.photos/seed/lampe/400'], vendor: 'Electro Plus', description: "Lampe de chevet au design moderne...", stock: 22, categoryId: 'sub-decoration', status: 'published', brand: 'HomeDecor' },
    { id: '24', name: 'Collier de perles', price: 9500, imageUrls: ['https://picsum.photos/seed/collier/400'], vendor: 'Kmer Fashion', description: "Collier artisanal...", stock: 30, categoryId: 'sub-bijoux', status: 'published', brand: 'Artisanat Local' },
    { id: '25', name: 'Montre Classique Homme', price: 32000, imageUrls: ['https://picsum.photos/seed/montre/400'], vendor: 'Electro Plus', description: "Montre élégante...", stock: 12, categoryId: 'sub-montres', status: 'published', brand: 'TimeMaster' },
    { id: '26', name: 'Poupée "Penda"', price: 7000, imageUrls: ['https://picsum.photos/seed/poupee/400'], vendor: 'Kmer Fashion', description: "Poupée en tissu pagne...", stock: 25, categoryId: 'sub-jouets-fournitures', status: 'published', brand: 'Artisanat Local' },
    { id: '27', name: 'Lot de 10 Cahiers', price: 2500, imageUrls: ['https://picsum.photos/seed/cahiers/400'], vendor: 'Electro Plus', description: "Un lot de 10 cahiers...", stock: 100, categoryId: 'sub-papeterie', status: 'published', brand: 'School Essentials' },
    { id: '28', name: 'Bière "33" Export (Pack de 6)', price: 4000, imageUrls: ['https://picsum.photos/seed/biere/400'], vendor: 'Mama Africa', description: "La bière blonde de référence...", stock: 50, categoryId: 'sub-autres-textiles', status: 'published' },
    { id: '29', name: 'Café Arabica en Grains', price: 6000, imageUrls: ['https://picsum.photos/seed/cafe/400'], vendor: 'Bafoussam Brews', description: "Café Arabica de l'Ouest Cameroun...", stock: 30, categoryId: 'sub-autres-textiles', status: 'published', brand: 'Bafoussam Brews' },
    { id: '30', name: 'Statuette en bois d\'ébène', price: 22000, imageUrls: ['https://picsum.photos/seed/statuette/400'], vendor: 'Limbe Arts & Crafts', description: "Statuette finement sculptée...", stock: 8, categoryId: 'sub-decoration', status: 'published', brand: 'Limbe Arts & Crafts' },
    { id: '31', name: 'Tableau d\'art contemporain', price: 48000, imageUrls: ['https://picsum.photos/seed/tableau/400'], vendor: 'Limbe Arts & Crafts', description: "Peinture sur toile vibrante...", stock: 3, categoryId: 'sub-decoration', status: 'published', brand: 'Limbe Arts & Crafts' },
    { id: '32', name: 'Écouteurs sans fil', price: 12500, imageUrls: ['https://picsum.photos/seed/ecouteurs/400'], vendor: 'Kribi Digital', description: "Écouteurs Bluetooth...", stock: 25, categoryId: 'sub-chargeurs-cables-batteries', status: 'draft' },
    { id: '33', name: 'Café Robusta Moulu', price: 4500, imageUrls: ['https://picsum.photos/seed/caferobusta/400'], vendor: 'Bafoussam Brews', description: "Café Robusta puissant...", stock: 40, categoryId: 'sub-autres-textiles', status: 'published', brand: 'Bafoussam Brews' },
];

export const initialStores = [
    { id: 'store-1', name: 'Kmer Fashion', sellerEmail: 'seller@example.com', category: 'Mode et Vêtements', status: 'active', location: 'Douala', neighborhood: 'Akwa', sellerFirstName: 'Aïcha', sellerLastName: 'Bakari', physicalAddress: '45 Avenue de la Mode, Akwa' },
    { id: 'store-2', name: 'Mama Africa', sellerEmail: 'mamaafrica@example.com', category: 'Alimentation', status: 'active', location: 'Yaoundé', neighborhood: 'Bastos', sellerFirstName: 'Jeanne', sellerLastName: 'Abena', physicalAddress: '12 Rue des Saveurs, Bastos' },
    { id: 'store-3', name: 'Electro Plus', sellerEmail: 'electro@example.com', category: 'Électronique', status: 'active', location: 'Yaoundé', neighborhood: 'Mokolo', sellerFirstName: 'Paul', sellerLastName: 'Kouam', physicalAddress: 'Grand Marché Mokolo, Stand 52' },
    { id: 'store-4', name: 'Douala Soaps', sellerEmail: 'soaps@example.com', category: 'Beauté et Hygiène', status: 'suspended', location: 'Douala', neighborhood: 'Bonapriso', sellerFirstName: 'Céline', sellerLastName: 'Ngassa', physicalAddress: 'Rue Njo-Njo, Bonapriso' },
    { id: 'store-5', name: 'Yaoundé Style', sellerEmail: 'yaoundestyle@example.com', category: 'Mode et Vêtements', status: 'pending', location: 'Yaoundé', neighborhood: 'Mvog-Ada', sellerFirstName: 'Franck', sellerLastName: 'Essomba', physicalAddress: 'Avenue Kennedy' },
    { id: 'store-6', name: 'Bafoussam Brews', sellerEmail: 'bafoussam@example.com', category: 'Alimentation & Boissons', status: 'active', location: 'Bafoussam', neighborhood: 'Centre Ville', sellerFirstName: 'Pierre', sellerLastName: 'Kamdem', physicalAddress: 'Marché Central, Bafoussam' },
    { id: 'store-7', name: 'Limbe Arts & Crafts', sellerEmail: 'limbearts@example.com', category: 'Artisanat & Décoration', status: 'active', location: 'Limbe', neighborhood: 'Down Beach', sellerFirstName: 'Sarah', sellerLastName: 'Eko', physicalAddress: 'Bord de mer, Limbe' },
    { id: 'store-8', name: 'Kribi Digital', sellerEmail: 'kribidigital@example.com', category: 'Électronique', status: 'pending', location: 'Kribi', neighborhood: 'Centre', sellerFirstName: 'David', sellerLastName: 'Lobe', physicalAddress: 'Avenue des Banques, Kribi' },
];
